#!/usr/bin/env sh

project=$1

cd "$project"

npm install -D

npx svelte-add@latest tailwindcss

npm install -D

npm install -D @leveluptuts/bookit@latest daisyui@latest

# TailwindCSS Installation
cp -f "$HOME/.sveltekit-init/tailwind/vite.config.ts" .
cp -f "$HOME/.sveltekit-init/tailwind/tailwind.config.cjs" .

# Bookit Installation
cp -r "$HOME/.sveltekit-init/bookit/book" "src/routes/"
cp -r "$HOME/.sveltekit-init/bookit/bookit" "src/bookit"
cp "$HOME/.sveltekit-init/bookit/+layout-root.svelte" "src/routes/"
